name: EasyMail
version: 1.0.1
main: me.xjuppo.easymail.EasyMail
api-version: 1.18
author: xJuppo

commands:
  easymail:
    description: Base command
    aliases: [ em ]
    usage: /<command> help for all commands